### ISSUE TITLE
?

### ISSUE THREAD

**Issue by movemente** [f0e/clipper#2]
When I tried running run.bat, it said this error.

![image](https://user-images.githubusercontent.com/87902551/147698692-f35e3448-41e2-4663-a3e1-eb314f355874.png)

**Comment by f0e** [comment]
This is a node v17 error, I got it too. Fixed when I downgraded to LTS.

**Comment by movemente** [comment]
That helped, thanks.
Now when I go in csgo and type clipper, it says it's a unknown command.

Also
![image](https://user-images.githubusercontent.com/87902551/147743444-ad9c8e42-03e3-4f25-950e-78b5a393606a.png)

**Comment by f0e** [comment]
What error showed up? You can change your settings at http://localhost:3000

**Comment by movemente** [comment]
![image](https://user-images.githubusercontent.com/87902551/147749511-8f78468d-e61d-433e-b20f-7aec1aa89b85.png)

I have no clue, but probably I'm just dumb

**Comment by f0e** [comment]
I might have just fixed it? Edited the file on my phone and I can't test it but give it a try

**Comment by movemente** [comment]
It doesn't give clipper not initialised.

It still says unknown command "clipper" in csgo.

**Comment by f0e** [comment]
Okay, I've got a few ideas on what's going on but I won't be able to test anything until tomorrow sorry. All I can say for now is make sure your config is correct (you can modify it in appdata/clipper if you need to), and that you've saved the gamestate cfg file and added the launch option.

**Comment by movemente** [comment]
Okay, thanks man.

**Comment by movemente** [comment]
Um..

**Comment by f0e** [comment]
should work as of e612d53bf102457159e1c8553c0e1a147deaed47 sorry i forgot abt this
